export default [
  {
    subject: 'expected impact',
    'Adorned Barcha': 8,
    'Born in War': 6,
    Breakthrough: 5,
    'Captive Audience': 4,
    'Cavalry Reserves': 6,
    'Challenge on the Fields': 5,
    'Curved Blade': 7,
    Dispatch: 4,
    'Favored Mount': 4,
    'Force of the River': 7,
    'Gaijin Customs': 6,
    'I Am Ready': 6,
    'Ide Messenger': 3,
    'Invocation of Ash': 5,
    'Iuchi Wayfinder': 4,
    'Jewel of the Khamasin': 5,
    Outflank: 4,
    'Press of Battle': 5,
    'Ride Them Down': 3,
    'Ring of Binding': 6,
    'Seal of the Unicorn': 4,
    fullMark: 10,
  },
  {
    subject: 'ease of usage',
    'Adorned Barcha': 5,
    'Born in War': 5,
    Breakthrough: 1,
    'Captive Audience': 6,
    'Cavalry Reserves': 5,
    'Challenge on the Fields': 8,
    'Curved Blade': 7,
    Dispatch: 6,
    'Favored Mount': 5,
    'Force of the River': 4,
    'Gaijin Customs': 4,
    'I Am Ready': 7,
    'Ide Messenger': 9,
    'Invocation of Ash': 9,
    'Iuchi Wayfinder': 9,
    'Jewel of the Khamasin': 5,
    Outflank: 3,
    'Press of Battle': 3,
    'Ride Them Down': 3,
    'Ring of Binding': 5,
    'Seal of the Unicorn': 4,
    fullMark: 10,
  },
  {
    subject: 'inexpensiveness',
    'Adorned Barcha': 6,
    'Born in War': 6,
    Breakthrough: 10,
    'Captive Audience': 9,
    'Cavalry Reserves': 4,
    'Challenge on the Fields': 10,
    'Curved Blade': 10,
    Dispatch: 8,
    'Favored Mount': 8,
    'Force of the River': 8,
    'Gaijin Customs': 8,
    'I Am Ready': 7,
    'Ide Messenger': 6,
    'Invocation of Ash': 8,
    'Iuchi Wayfinder': 8,
    'Jewel of the Khamasin': 6,
    Outflank: 10,
    'Press of Battle': 10,
    'Ride Them Down': 5,
    'Ring of Binding': 8,
    'Seal of the Unicorn': 10,
    fullMark: 10,
  },
  {
    subject: 'self synergy',
    'Adorned Barcha': 4,
    'Born in War': 5,
    Breakthrough: 4,
    'Captive Audience': 3,
    'Cavalry Reserves': 4,
    'Challenge on the Fields': 6,
    'Curved Blade': 6,
    Dispatch: 4,
    'Favored Mount': 3,
    'Force of the River': 6,
    'Gaijin Customs': 5,
    'I Am Ready': 5,
    'Ide Messenger': 4,
    'Invocation of Ash': 5,
    'Iuchi Wayfinder': 4,
    'Jewel of the Khamasin': 2,
    Outflank: 4,
    'Press of Battle': 4,
    'Ride Them Down': 3,
    'Ring of Binding': 4,
    'Seal of the Unicorn': 3,
    fullMark: 10,
  },
]
