export default [
  {
    name: 'Adorned Barcha',
    'Expected Impact': 9,
    'Ease of Use': 5,
    Inexpensiveness: 4,
    'Self Synergy': 4,
  },
  {
    name: 'Born in War',
    'Expected Impact': 7,
    'Ease of Use': 5,
    Inexpensiveness: 4,
    'Self Synergy': 5,
  },
  {
    name: 'Breakthrough',
    'Expected Impact': 5,
    'Ease of Use': 1,
    Inexpensiveness: 8,
    'Self Synergy': 4,
  },
  {
    name: 'Captive Audience',
    'Expected Impact': 5,
    'Ease of Use': 6,
    Inexpensiveness: 7,
    'Self Synergy': 3,
  },
  {
    name: 'Cavalry Reserves',
    'Expected Impact': 8,
    'Ease of Use': 5,
    Inexpensiveness: 2,
    'Self Synergy': 4,
  },
  {
    name: 'Challenge on the Fields',
    'Expected Impact': 5,
    'Ease of Use': 8,
    Inexpensiveness: 8,
    'Self Synergy': 6,
  },
  {
    name: 'Curved Blade',
    'Expected Impact': 8,
    'Ease of Use': 7,
    Inexpensiveness: 8,
    'Self Synergy': 6,
  },
  {
    name: 'Dispatch',
    'Expected Impact': 4,
    'Ease of Use': 6,
    Inexpensiveness: 6,
    'Self Synergy': 4,
  },
  {
    name: 'Favored Mount',
    'Expected Impact': 4,
    'Ease of Use': 5,
    Inexpensiveness: 6,
    'Self Synergy': 3,
  },
  {
    name: 'Force of the River',
    'Expected Impact': 7,
    'Ease of Use': 4,
    Inexpensiveness: 6,
    'Self Synergy': 6,
  },
  {
    name: 'Gaijin Customs',
    'Expected Impact': 7,
    'Ease of Use': 4,
    Inexpensiveness: 6,
    'Self Synergy': 5,
  },
  {
    name: 'I Am Ready',
    'Expected Impact': 7,
    'Ease of Use': 7,
    Inexpensiveness: 5,
    'Self Synergy': 5,
  },
  {
    name: 'Ide Messenger',
    'Expected Impact': 4,
    'Ease of Use': 9,
    Inexpensiveness: 4,
    'Self Synergy': 4,
  },
  {
    name: 'Invocation of Ash',
    'Expected Impact': 6,
    'Ease of Use': 9,
    Inexpensiveness: 6,
    'Self Synergy': 5,
  },
  {
    name: 'Iuchi Wayfinder',
    'Expected Impact': 5,
    'Ease of Use': 9,
    Inexpensiveness: 6,
    'Self Synergy': 4,
  },
  {
    name: 'Jewel of the Khamasin',
    'Expected Impact': 5,
    'Ease of Use': 5,
    Inexpensiveness: 4,
    'Self Synergy': 2,
  },
  {
    name: 'Outflank',
    'Expected Impact': 4,
    'Ease of Use': 3,
    Inexpensiveness: 8,
    'Self Synergy': 4,
  },
  {
    name: 'Press of Battle',
    'Expected Impact': 5,
    'Ease of Use': 3,
    Inexpensiveness: 8,
    'Self Synergy': 4,
  },
  {
    name: 'Ride Them Down',
    'Expected Impact': 3,
    'Ease of Use': 3,
    Inexpensiveness: 3,
    'Self Synergy': 3,
  },
  {
    name: 'Ring of Binding',
    'Expected Impact': 6,
    'Ease of Use': 5,
    Inexpensiveness: 6,
    'Self Synergy': 4,
  },
  {
    name: 'Seal of the Unicorn',
    'Expected Impact': 4,
    'Ease of Use': 4,
    Inexpensiveness: 8,
    'Self Synergy': 3,
  },
  {
    name: 'Shiksha Scout',
    'Expected Impact': 4,
    'Ease of Use': 8,
    Inexpensiveness: 4,
    'Self Synergy': 5,
  },
  {
    name: 'Shinjo Ambusher',
    'Expected Impact': 6,
    'Ease of Use': 8,
    Inexpensiveness: 6,
    'Self Synergy': 4,
  },
  {
    name: 'Shinjo Haruko',
    'Expected Impact': 6,
    'Ease of Use': 8,
    Inexpensiveness: 2,
    'Self Synergy': 6,
  },
  {
    name: 'Shinjo Saddle',
    'Expected Impact': 4,
    'Ease of Use': 7,
    Inexpensiveness: 6,
    'Self Synergy': 5,
  },
  {
    name: 'Shinomen Wayfinders',
    'Expected Impact': 6,
    'Ease of Use': 5,
    Inexpensiveness: 6,
    'Self Synergy': 7,
  },
  {
    name: 'Speak to the Heart',
    'Expected Impact': 5,
    'Ease of Use': 6,
    Inexpensiveness: 8,
    'Self Synergy': 4,
  },
  {
    name: 'Spoils of War',
    'Expected Impact': 8,
    'Ease of Use': 7,
    Inexpensiveness: 8,
    'Self Synergy': 4,
  },
  {
    name: 'Spyglass',
    'Expected Impact': 9,
    'Ease of Use': 6,
    Inexpensiveness: 6,
    'Self Synergy': 5,
  },
  {
    name: 'Talisman of the Sun',
    'Expected Impact': 8,
    'Ease of Use': 7,
    Inexpensiveness: 6,
    'Self Synergy': 4,
  },
  {
    name: 'Ujik Tactics',
    'Expected Impact': 7,
    'Ease of Use': 3,
    Inexpensiveness: 8,
    'Self Synergy': 5,
  },
  {
    name: 'Utaku Battle Steed',
    'Expected Impact': 6,
    'Ease of Use': 6,
    Inexpensiveness: 6,
    'Self Synergy': 4,
  },
  {
    name: 'Visiting Advisor',
    'Expected Impact': 5,
    'Ease of Use': 9,
    Inexpensiveness: 4,
    'Self Synergy': 4,
  },
  {
    name: 'Warriors of the Wind',
    'Expected Impact': 7,
    'Ease of Use': 2,
    Inexpensiveness: 4,
    'Self Synergy': 3,
  },
  {
    name: 'Way of the Unicorn',
    'Expected Impact': 3,
    'Ease of Use': 7,
    Inexpensiveness: 8,
    'Self Synergy': 4,
  },
]
